var GAPIKey='AIzaSyAe4YMd9fMYrGEs8Xw2M_AXVydFcAeTrb8' //for google Maps
var FCLIENT_ID='XA0UNJTT3PTHMRZFN0EUIKSEYCN0JS0T2CYMC5CEGVOLLUYU' //for FourSquare Client ID
var FCLIENT_SEC='FGPXHDRFGUJUTCK1UR5M5E54H4REW3E42BXBPGCD4EUW3MGG' //for FourSquare Client Secret

export {GAPIKey,FCLIENT_ID,FCLIENT_SEC}
